// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvmzhjybjwprtupogumd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52bXpoanliandwcnR1cG9ndW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNjUzNjEsImV4cCI6MjA5MDY0MTM2MX0.7G68xu-731DQM8jVKKT_3qxktTLJP5RfdPstWUMsaEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});